### ISSUE TITLE
Export MomentDateTimeAdapter

### ISSUE THREAD

**Issue by Olusha** [danielmoncada/date-time-picker-moment-adapter#9]
MomentDateTimeAdapter should be exported in public-api.ts.

**Comment by JoostK** [comment]
To add some context as to why it's useful to have access to `MomentDateTimeAdapter`: we have a scenario where localization configuration is only available within sub-parts of the applications, resulting in us overriding `OWL_DATE_TIME_LOCALE`/`OWL_DATE_TIME_FORMATS` using `Component.providers`. Since these tokens are injected into `MomentDateTimeAdapter` we also need to create a new instance of that service at the component level, but there is no way to provide the service since `MomentDateTimeAdapter` is not exported.

**Comment by salimchemes** [comment]
Sorrt, i am still see MomentDateTimeAdapter not exported

**Comment by JoostK** [comment]
Hmm indeed, #10 was a noop change.

**Comment by danielmoncada** [comment]
yeah sorry guys.. not sure what happened that (guessing I didn't save the file). here's the new PR: https://github.com/danielmoncada/date-time-picker-moment-adapter/pull/11

**Comment by danielmoncada** [comment]
new version up: https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker-moment-adapter/v/2.2.0
